### ISSUE TITLE
Defi-App Translation Bounty Program

### ISSUE THREAD

**Issue by monstrobishi** [DeFiCh/defi-app#10]
# Defi-App Translation Bounty Program

## Intro

Following the recent release of our dedicated desktop wallet, we would like to continue to enhance and improve the user experience for all users. As part of this initiative, we are planning to offer the desktop wallet app in a variety of languages, and we would like you to get involved!

The Defichain Foundation will be offering a bounty of **150 DFI** for assistance in translating the app into a new language. The process is simple:
- Fork the existing repository
- Edit the translation files (More on that below)
- Submit a PR

Our team will do the rest of the heavy lifting of integrating the translation back into the app. Note that the bounty will only be given to the person to submit an *accurate* and *useful* translation as a PR for any particular language. 

**Important Note**: Before beginning work on a language, leave a comment under this issue as to what language you would like to translate into, and wait for approval, as we may not want a translation into pig-latin for example.

## How to edit the files

Translation files are JSON files that are located under `webapp/src/translations/languages`, for instance the existing English translation is called `en.json`. Here is a snippet from that file:

```json
"syncStatus": {
  "synchronized": "Synchronized",
  "syncing": "Synchronizing",
  "synced": "Synced",
  "justNow": "Synchronized just now",
  "aMinuteAgo": "Synchronized a minute ago",
  "blockInfo": "Block %{latestSyncedBlock} of %{latestBlock}"
}
```

In order to provide a translation, copy the English translation file, rename it to `yourLanguage.json` inside the translation directory, and then simply alter the content of each of the dictionary keys to represent the same meaning in your particular language.

## Receiving the bounty

Bounties will be paid out in DFI to your address once the community has reviewed and approved your translation.

For any further queries contact us at engineering@defichain.com

## Bounties

- French #23 (Thanks @huguesk. [150 DFI bounty transferred](https://explorer.defichain.io/#/DFI/mainnet/tx/7c896510a6450496ef70e11a6caa05c2f95e148a629543f8161f187cd37cadc9).)

**Comment by huguesk** [comment]
Hi, is French of any interest? I could help with it. Is there a deadline?

**Comment by monstrobishi** [comment]
@huguesk You have our approval, go ahead and do it! There is no specific deadline, if you are the first person to submit for that specific language, you will receive the bounty :)

**Comment by huguesk** [comment]
@monstrobishi, I could't figure out how to send you the file via GitHub.... (#embarrassing) so I sent it per mail at engineering@defichain.com. Hope this is ok :)

**Comment by uzyn** [comment]
@huguesk can you open a PR for it? Otherwise @monstrobishi can you assist to open a PR on @huguesk 's behalf for transparency? Please also post your DFI address on the PR.

We'll consult our userbase to vouch for the translation, hopefully we have some francophone community users.

**Comment by fullstackninja864** [comment]
@huguesk Can you provide the translation for the given missing translation object

```
"alerts": {
  "masterNodeOperatorAddressFailure": "Masternode operator address is not present",
    "restartNode": "Restarting Node",
    "nodeDisconnected": "Node is disconnected",
    "electronRequiredError": "Electron app is needed for restart"
},
"containers": {
  "masterNodes" {
    "createMasterNode": {
      "restartNodeButton": "Restart node",
      "masterNodeSuccess": "You can manually set masternode config in defi.conf or you can automatic set this masternode config by restarting the node."
    }
  }
}
```

**Comment by huguesk** [comment]
@fullstackninja864 here it is:

"alerts": {
  "masterNodeOperatorAddressFailure": "L'adresse de l'opérateur du nœud complet est manquante",
    "restartNode": "Redémarrage du nœud",
    "nodeDisconnected": "Le nœud est déconnecté",
    "electronRequiredError": "L'application Electron est nécéssaire pour le redémarrage"
},
"containers": {
  "masterNodes" {
    "createMasterNode": {
      "restartNodeButton": "Redémarrer le nœud",
      "masterNodeSuccess": "Vous pouvez définir manuellement la configuration du nœud sous defi.conf ou la définir automatiquement en redémarrant le nœud."
    }
  }
}

**Comment by huguesk** [comment]
@fullstackninja864 here it is:

"alerts": {
  "masterNodeOperatorAddressFailure": "L'adresse de l'opérateur du nœud complet est manquante",
    "restartNode": "Redémarrage du nœud",
    "nodeDisconnected": "Le nœud est déconnecté",
    "electronRequiredError": "L'application Electron est nécéssaire pour le redémarrage"
},
"containers": {
  "masterNodes" {
    "createMasterNode": {
      "restartNodeButton": "Redémarrer le nœud",
      "masterNodeSuccess": "Vous pouvez définir manuellement la configuration du nœud sous defi.conf ou la définir automatiquement en redémarrant le nœud."
    }
  }
}

**Comment by huguesk** [comment]
@fullstackninja864 here it is:
`"alerts": {
"masterNodeOperatorAddressFailure": "L'adresse de l'opérateur du nœud complet est manquante",
"restartNode": "Redémarrage du nœud",
"nodeDisconnected": "Le nœud est déconnecté",
"electronRequiredError": "L'application Electron est nécéssaire pour le redémarrage"
},
"containers": {
"masterNodes" {
"createMasterNode": {
"restartNodeButton": "Redémarrer le nœud",
"masterNodeSuccess": "Vous pouvez définir manuellement la configuration du nœud sous defi.conf ou la définir automatiquement en redémarrant le nœud."
}
}
}`

**Comment by huguesk** [comment]
@fullstackninja864 here it is:

"alerts": {
"masterNodeOperatorAddressFailure": "L'adresse de l'opérateur du nœud complet est manquante",
"restartNode": "Redémarrage du nœud",
"nodeDisconnected": "Le nœud est déconnecté",
"electronRequiredError": "L'application Electron est nécéssaire pour le redémarrage"
},
"containers": {
"masterNodes" {
"createMasterNode": {
"restartNodeButton": "Redémarrer le nœud",
"masterNodeSuccess": "Vous pouvez définir manuellement la configuration du nœud sous defi.conf ou la définir automatiquement en redémarrant le nœud."
}
}
}

**Comment by LLKKC** [comment]
Hi, I am sure that Slovenian is not high on your list of priorities, however if you are interested, I can offer you professional translation into Slovenian. All the best with your project!

**Comment by uzyn** [comment]
> Hi, I am sure that Slovenian is not high on your list of priorities, however if you are interested, I can offer you professional translation into Slovenian. All the best with your project!

That would be nice, @LLKKC ! Any Slovenian speakers or users here? If yes we would be happy to offer the bounty for Slovenian translation, also to help to vouch for the accuracy of the translation.

**Comment by LLKKC** [comment]
Hi, thanks for your quick reply. Well I know quite a lot of people dealing with cryptocurrencies and Defi seems to be very popular right now, so I would like to do all I can to assist adoption. I will proceed with the translation and will send you the file by e-mail later today, if that is okay.

**Comment by biterminator** [comment]
Hi.
I can translate to Croatian and Serbian languages.

**Comment by sergejmueller** [comment]
Suggestion: Russian language

**Comment by LLKKC** [comment]
Hi, please note that I have forked the existing depository, translated the file and saved it under sl.json as per your instructions. Please contact me should you require any further assistance.

**Comment by pshtuk** [comment]
Hey! I can offer translations into both Danish and Norwegian, if this would be of any interest.

**Comment by coup3z** [comment]
Hello everybody. I have translated the file in Romanian. Do I sent it to engineering@defichain.com or just paste it here?

**Comment by sergejmueller** [comment]
> Hello everybody. I have translated the file in Romanian. Do I sent it to [engineering@defichain.com](mailto:engineering@defichain.com) or just paste it here?

From the post above ;)
"Important Note: Before beginning work on a language, leave a comment under this issue as to what language you would like to translate into, and wait for approval, as we may not want a translation into pig-latin for example."

**Comment by coup3z** [comment]
> > Hello everybody. I have translated the file in Romanian. Do I sent it to [engineering@defichain.com](mailto:engineering@defichain.com) or just paste it here?
> 
> From the post above ;)
> "Important Note: Before beginning work on a language, leave a comment under this issue as to what language you would like to translate into, and wait for approval, as we may not want a translation into pig-latin for example."

yeah. no problem. if you don't use you don't use it, i don't expect any bounty. but if you use it in the future, you have it attached in the previous post.

**Comment by sergejmueller** [comment]
@monstrobishi Any approvals?

**Comment by Brecht-H** [comment]
Do you still need someone for a translation into Dutch?

**Comment by monstrobishi** [comment]
We are moving Defi-App to the Defi-App 2 repo, this issue will be closed and duplicated to the Defi-App 2 repo, we will tag and respond to existing requests over there.

Here is the new issue: https://github.com/DeFiCh/defi-app-2/issues/11

Thank you
